# Generated by Django 5.1 on 2024-08-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_uploadedfile_filelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
