# Generated by Django 5.1 on 2024-08-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_uploadedfile_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileLink',
        ),
    ]
