# Generated by Django 5.1 on 2024-09-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_videolink'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderlar',
            name='pdflink1',
            field=models.URLField(blank=True, null=True, verbose_name='PDF ссылка 1'),
        ),
        migrations.AddField(
            model_name='tenderlar',
            name='pdflink10',
            field=models.URLField(blank=True, null=True, verbose_name='PDF ссылка 10'),
        ),
        migrations.AddField(
            model_name='tenderlar',
            name='pdflink11',
            field=models.URLField(blank=True, null=True, verbose_name='PDF ссылка 11'),
        ),
        migrations.AddField(
            model_name='tenderlar',
            name='pdflink12',
            field=models.URLField(blank=True, null=True, verbose_name='PDF ссылка 12'),
        ),
        migrations.AddField(
            model_name='tenderlar',
            name='pdflink2',
            field=models.URLField(blank=True, null=True, verbose_name='PDF ссылка 2'),
        ),
        migrations.AddField(
            model_name='tenderlar',
            name='pdflink3',
            field=models.URLField(blank=True, null=True, verbose_name='PDF ссылка 3'),
        ),
        migrations.AddField(
            model_name='tenderlar',
            name='pdflink4',
            field=models.URLField(blank=True, null=True, verbose_name='PDF ссылка 4'),
        ),
        migrations.AddField(
            model_name='tenderlar',
            name='pdflink5',
            field=models.URLField(blank=True, null=True, verbose_name='PDF ссылка 5'),
        ),
        migrations.AddField(
            model_name='tenderlar',
            name='pdflink6',
            field=models.URLField(blank=True, null=True, verbose_name='PDF ссылка 6'),
        ),
        migrations.AddField(
            model_name='tenderlar',
            name='pdflink7',
            field=models.URLField(blank=True, null=True, verbose_name='PDF ссылка 7'),
        ),
        migrations.AddField(
            model_name='tenderlar',
            name='pdflink8',
            field=models.URLField(blank=True, null=True, verbose_name='PDF ссылка 8'),
        ),
        migrations.AddField(
            model_name='tenderlar',
            name='pdflink9',
            field=models.URLField(blank=True, null=True, verbose_name='PDF ссылка 9'),
        ),
    ]
